/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/client" />

/// `artefact-wasm` is generated by `just build wasm` into a gitignored
/// directory, so CI has no `.d.ts` for it. Alias it in `vite.config.ts` and
/// declare the surface we use here to keep `vue-tsc` runnable without a build.
declare module 'artefact-wasm' {
	export enum OutputFormat {
		Png = 0,
		Webp = 1,
		Tiff = 2,
		Bmp = 3
	}

	export function compute(
		buffer: Uint8Array,
		output_format: OutputFormat,
		weight: number,
		pweight: number,
		iterations: number,
		separate_components: boolean,
		use_gpu: boolean
	): Promise<Uint8Array>

	export default function init(): Promise<unknown>
}
