[package]
name = "artefact-wasm"
version.workspace = true
edition.workspace = true

[dependencies]
artefact-core = { workspace = true, features = ["simd", "gpu"] }
console_error_panic_hook = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[lib]
name = "artefact_wasm"
path = "lib.rs"
crate-type = ["cdylib"]
