[workspace]
resolver = "2"
members = ["backend/artefact-cli", "backend/artefact-core", "backend/artefact-wasm", "backend/zune-jpeg"]

[workspace.dependencies]
artefact-core = { path = "backend/artefact-core" }
bytemuck = { version = "1", features = ["derive"] }
clap = { version = "4.5.23", features = ["derive"] }
console_error_panic_hook = { version = "0.1.7" }
criterion = { version = "0.8.2" }
image = { version = "0.25.8", default-features = false, features = ["png", "webp", "bmp", "tiff"] }
pollster = "1.0"
rand = { version = "0.10.2" }
rand_core = { version = "0.10.1" }
rayon = { version = "1.11.0" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
wasm-bindgen = { version = "0.2.104" }
wasm-bindgen-futures = { version = "0.4.54" }
wgpu = "=30.0.1"
zune-core = { version = "0.5.0-rc2" }
zune-jpeg = { path = "backend/zune-jpeg" }
zune-ppm = { version = "0.5.0-rc0" }

[profile.release]
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
