[workspace]
resolver = "2"
members = ["backend/artefact-cli", "backend/artefact-lib", "backend/artefact-wasm", "backend/zune-jpeg"]

[profile.release]
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
