[package]
name = "artefact-core"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
zune-jpeg = { workspace = true }
mozjpeg-sys = { workspace = true, optional = true }
wide = { workspace = true, optional = true }
rayon = { workspace = true }
thiserror = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
paste = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
wide = { workspace = true }

[lib]
name = "artefact_core"
path = "lib.rs"

[features]
simd = ["dep:wide"]
simd_std = []
simd_adaptive = []
native = []
moz = ["dep:mozjpeg-sys", "dep:thiserror", "dep:libc"]

[[bench]]
name = "bench"
harness = false
