[package]
name = "artefact-core"
version = "0.1.0"
edition = "2024"
autobenches = false

[dependencies]
image = { workspace = true }
zune-jpeg = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
pollster = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }

[lib]
name = "artefact_core"
path = "lib.rs"

[features]
simd = []
gpu = ["dep:wgpu", "dep:bytemuck"]
bench = []

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "alloc_stats"
harness = false

[[test]]
name = "tv_equivalence"
required-features = ["bench"]
