[package]
name = "artefact-cli"
version = "1.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[dependencies.artefact-lib]
path = "../artefact-lib"
features = ["native", "simd", "simd_std", "simd_adaptive"]

[[bin]]
name = "artefact-cli"
path = "main.rs"
