[package]
name = "artefact-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
image = { version = "0.25.5", default-features = false, features = ["png"] }
zune-jpeg = { path = "../zune-jpeg" }

[lib]
name = "artefact_lib"
path = "lib.rs"
