[package]
name = "artefact-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
anyhow = "1.0.94"
image = { version = "0.25.5", default-features = false, features = ["png"] }
zune-jpeg = { path = "../zune-jpeg" }
thiserror = "2.0.9"

[lib]
name = "artefact_lib"
path = "lib.rs"
