[package]
name = "artefact-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
artefact-core = { workspace = true, features = ["simd", "gpu"] }
clap = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "artefact-cli"
path = "main.rs"
