[package]
name = "artefact-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.99"
artefact-lib = { path = "../artefact-lib", features = ["simd"] }
console_error_panic_hook = "0.1.7"

[lib]
name = "artefact_wasm"
path = "lib.rs"
crate-type = ["cdylib"]